### ISSUE TITLE
Crash when breaking Iron furnace industrialcraft-2-2.8.196-ex112 & forge-1.12.2-14.23.5.2846

### ISSUE THREAD

**Issue by velocityraptor-real** [MineExplorer/IndustrialCraft_2#49]
Game crashes when starting to break the Block
Crash report:
[crash-2020-04-14_18.47.42-client.txt](https://github.com/MineExplorer/IndustrialCraft_2/files/4476634/crash-2020-04-14_18.47.42-client.txt)
Latest log:
[latest.log](https://github.com/MineExplorer/IndustrialCraft_2/files/4476640/latest.log)

Might be a compatibility issue

**Comment by velocityraptor-real** [comment]
Breaking industrialcraft blocks with a shickaxe from divineRPG makes the game to crash.
Blockbreaking works with vanilla tools

**Comment by MineExplorer** [comment]
LOL it isn't original IC2 repository, it is version for Minecraft Bedrock on Android and I am not associated with original IC2 developers on Java Edition.
