### ISSUE TITLE
IC2 Crash Report in my Minecraft Modpack

### ISSUE THREAD

**Issue by Deniz-seckin55** [MineExplorer/IndustrialCraft_2#69]
There is the crash report and log :

crash-report : https://gist.github.com/Deniz-seckin55/a623c2b1660a902f2f47629e73901e4b
log : https://gist.github.com/Deniz-seckin55/3f88b4c01afc857be463b2efc6ffc2c8

Thanks.

**Comment by MineExplorer** [comment]
I'm sorry, but it's unofficial port of IC2 for PC to Minecraft on Android powered by Inner Core modloader. I'm not associated with IC2 developer team whose develop original mod for PC.
